In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\sql project inno\sql project data\employee.csv")
df

,employee_id,last_name,first_name,title,reports_to,levels,birthdate,hire_date,address,city,state,country,postal_code,phone,fax,email
0,1,Adams,Andrew,General Manager,9.0,L6,02/18/1962,08/14/2016,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,L4,12/08/1958,05/01/2016,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,L1,08/29/1973,04/01/2017,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,L1,09/19/1947,05/03/2017,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,L1,03/03/1965,10/17/2017,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,L3,07/01/1973,10/17/2016,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,L2,05/29/1970,01/02/2017,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,L2,01/09/1968,03/04/2017,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com
8,9,Madan,Mohan,Senior General Manager,NaN,L7,01/26/1961,01/14/2016,1008 Vrinda Ave MT,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,madan.mohan@chinookcorp.com

In [6]:
df["reports_to"].fillna(0,inplace=True)

C:\Users\AJAY\AppData\Local\Temp\ipykernel_8128\535883063.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["reports_to"].fillna(0,inplace=True)

In [7]:
df

,employee_id,last_name,first_name,title,reports_to,levels,birthdate,hire_date,address,city,state,country,postal_code,phone,fax,email
0,1,Adams,Andrew,General Manager,9.0,L6,02/18/1962,08/14/2016,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,L4,12/08/1958,05/01/2016,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,L1,08/29/1973,04/01/2017,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,L1,09/19/1947,05/03/2017,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,L1,03/03/1965,10/17/2017,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,L3,07/01/1973,10/17/2016,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,L2,05/29/1970,01/02/2017,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,L2,01/09/1968,03/04/2017,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com
8,9,Madan,Mohan,Senior General Manager,0.0,L7,01/26/1961,01/14/2016,1008 Vrinda Ave MT,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,madan.mohan@chinookcorp.com

In [ ]:
# converted mm/dd/yyyy to yyyy/mm/dd .because it accepts only yyyy/mm/dd datae format

In [13]:
df["birthdate"] = ["1962/02/18" , "1958/12/08"
,"1973/08/29"
,   "1947/09/19"
,    "1965/03/03"
,   "1973/07/01"
,   "1970/05/29"
,   "1968/01/09"
,    "1961/01/26"]

In [18]:
df["hire_date"]= ['2016/08/14',
 '2016/05/01',
 '2017/04/01',
 '2017/05/03',
 '2017/10/17',
 '2016/10/17',
 '2017/01/02',
 '2017/03/04',
 '2016/01/14']

In [19]:
df

,employee_id,last_name,first_name,title,reports_to,levels,birthdate,hire_date,address,city,state,country,postal_code,phone,fax,email
0,1,Adams,Andrew,General Manager,9.0,L6,1962/02/18,2016/08/14,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,L4,1958/12/08,2016/05/01,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,L1,1973/08/29,2017/04/01,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,L1,1947/09/19,2017/05/03,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,L1,1965/03/03,2017/10/17,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,L3,1973/07/01,2016/10/17,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,L2,1970/05/29,2017/01/02,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,L2,1968/01/09,2017/03/04,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com
8,9,Madan,Mohan,Senior General Manager,0.0,L7,1961/01/26,2016/01/14,1008 Vrinda Ave MT,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,madan.mohan@chinookcorp.com

In [20]:
df.to_csv("D:\sql project inno\sql project data\employee(updated).csv",index=False)

In [38]:
df = pd.read_csv(r"D:\sql project inno\sql project data\track.csv")

In [40]:
df.isnull().sum()

track_id           0
name               0
album_id           0
media_type_id      0
genre_id           0
composer         978
milliseconds       0
bytes              0
unit_price         0
dtype: int64

In [41]:
# in sql if you mention varchar then it should not contains the null values .if contains it remove entire row while importing the data(csv files)

In [42]:
df["composer"].fillna("blank_space",inplace=True)

C:\Users\AJAY\AppData\Local\Temp\ipykernel_8128\4114469308.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["composer"].fillna("blank_space",inplace=True)

In [43]:
df.isnull().sum()

track_id         0
name             0
album_id         0
media_type_id    0
genre_id         0
composer         0
milliseconds     0
bytes            0
unit_price       0
dtype: int64

In [44]:
df.to_csv(r"D:\sql project inno\sql project data\track(updated).csv",index=False)